services:
  kitCaddyWsc:
    image: kvalitetsit/kitcaddy:1.3.18
    volumes:
      - ./wscCerts:/cert
      - ./stsCerts/sts.cer:/trust/sts.cer
      - ./config:/config
    command: -config ./config/Caddyfile-wsc.json
    ports:
      - "8080:80"
  mongo:
    image: mongo:3.6
